# -*- coding: utf-8 -*-
"""C-RAG APP.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JbK7ZKsc8Ftvfuzk9qyar5m4Eds8P6-4
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import os # Import os to access environment variables
# 
# from typing import List, TypedDict, Literal
# from pydantic import BaseModel
# import re
# 
# from langchain_community.document_loaders import PyPDFLoader
# from langchain_community.vectorstores import FAISS
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_core.documents import Document
# from langchain_core.prompts import ChatPromptTemplate
# 
# from langchain_huggingface import HuggingFaceEmbeddings
# from langchain_groq import ChatGroq
# from langchain_community.tools.tavily_search import TavilySearchResults
# 
# from langgraph.graph import StateGraph, START, END
# 
# # --- API Key Loading (from Colab Secrets as environment variables) ---
# # Streamlit applications cannot directly access userdata.get().
# # API keys will be passed as environment variables when the app is launched.
# GROQ_API_KEY = os.getenv("GROQ_API_KEY")
# TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")
# 
# # --- Global Thresholds (from notebook) ---
# UPPER_TH = 0.7
# LOWER_TH = 0.3
# 
# # --- State Definition (from notebook) ---
# class State(TypedDict):
#     question: str
#     docs: List[Document]
#     good_docs: List[Document]
#     verdict: str
#     reason: str
#     strips: List[str]
#     kept_strips: List[str]
#     refined_context: str
#     web_query: str
#     web_docs: List[Document]
#     answer: str
# 
# # --- Helper Functions (from notebook) ---
# def decompose_to_sentences(text: str) -> List[str]:
#     text = re.sub(r"\s+", " ", text).strip()
#     sentences = re.split(r"(?<=[.!?])\s+", text)
#     return [s.strip() for s in sentences if len(s.strip()) > 20]
# 
# # --- Model and Embeddings Initialization ---
# @st.cache_resource
# def load_rag_components():
#     # Load PDFs and create chunks
#     docs = (
#         PyPDFLoader("/content/book1.pdf").load()
#         + PyPDFLoader("/content/book2.pdf").load()
#         + PyPDFLoader("/content/book3.pdf").load()
#     )
#     chunks = RecursiveCharacterTextSplitter(chunk_size=900, chunk_overlap=150).split_documents(docs)
#     for d in chunks:
#         d.page_content = d.page_content.encode("utf-8", "ignore").decode("utf-8", "ignore")
# 
#     # Initialize embeddings, vector store, and retriever
#     embeddings = HuggingFaceEmbeddings(
#         model_name="sentence-transformers/all-MiniLM-L6-v2"
#     )
#     vector_store = FAISS.from_documents(chunks, embeddings)
#     retriever = vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 4})
# 
#     # Initialize LLM
#     llm = ChatGroq(
#         model="llama-3.3-70b-versatile",
#         temperature=0,
#         api_key=GROQ_API_KEY
#     )
# 
#     # Initialize Tavily tool
#     tavily = TavilySearchResults(max_results=5, tavily_api_key=TAVILY_API_KEY)
# 
#     # --- Node-specific classes and chains (from notebook) ---
#     class DocEvalScore(BaseModel):
#         score: float
#         reason: str
# 
#     doc_eval_prompt = ChatPromptTemplate.from_messages(
#         [
#             (
#                 "system",
#                 "You are a strict retrieval evaluator for RAG.\n"
#                 "You will be given ONE retrieved chunk and a question.\n"
#                 "Return a relevance score in [0.0, 1.0].\n"
#                 "- 1.0: chunk alone is sufficient to answer fully/mostly\n"
#                 "- 0.0: chunk is irrelevant\n"
#                 "Be conservative with high scores.\n"
#                 "Also return a short reason.\n"
#                 "Output JSON only.",
#             ),
#             ("human", "Question: {question}\n\nChunk:\n{chunk}"),
#         ]
#     )
#     doc_eval_chain = doc_eval_prompt | llm.with_structured_output(DocEvalScore)
# 
#     class KeepOrDrop(BaseModel):
#         keep: bool
# 
#     filter_prompt = ChatPromptTemplate.from_messages(
#         [
#             (
#                 "system",
#                 "You are a strict relevance filter. Your task is to determine if a given sentence directly helps answer a question. Return a JSON object with a single key, 'keep', set to 'true' (boolean) if it helps, otherwise 'false' (boolean). Use ONLY the sentence provided. Output JSON only.",
#             ),
#             ("human", "Question: {question}\n\nSentence:\n{sentence}"),
#         ]
#     )
#     filter_chain = filter_prompt | llm.with_structured_output(KeepOrDrop)
# 
#     class WebQuery(BaseModel):
#         query: str
# 
#     rewrite_prompt = ChatPromptTemplate.from_messages(
#         [
#             (
#                 "system",
#                 "Rewrite the user question into a web search query composed of keywords.\n"
#                 "Rules:\n"
#                 "- Keep it short (6–14 words).\n"
#                 "- If the question implies recency (e.g., recent/latest/last week/last month), add a constraint like (last 30 days).\n"
#                 "- Do NOT answer the question.\n"
#                 "- Return JSON with a single key: query",
#             ),
#             ("human", "Question: {question}"),
#         ]
#     )
#     rewrite_chain = rewrite_prompt | llm.with_structured_output(WebQuery)
# 
#     # --- Graph Node Functions (from notebook) ---
#     def retrieve_node(state: State) -> State:
#         q = state["question"]
#         return {"docs": retriever.invoke(q)}
# 
#     def eval_each_doc_node(state: State) -> State:
#         q = state["question"]
#         scores: List[float] = []
#         good: List[Document] = []
# 
#         for d in state["docs"]:
#             out = doc_eval_chain.invoke({"question": q, "chunk": d.page_content})
#             scores.append(out.score)
# 
#             if out.score > LOWER_TH:
#                 good.append(d)
# 
#         if any(s > UPPER_TH for s in scores):
#             return {
#                 "good_docs": good,
#                 "verdict": "CORRECT",
#                 "reason": f"At least one retrieved chunk scored > {UPPER_TH}.",
#             }
#         if len(scores) > 0 and all(s < LOWER_TH for s in scores):
#             return {
#                 "good_docs": [],
#                 "verdict": "INCORRECT",
#                 "reason": f"All retrieved chunks scored < {LOWER_TH}.",
#             }
#         return {
#             "good_docs": good,
#             "verdict": "AMBIGUOUS",
#             "reason": f"No chunk scored > {UPPER_TH}, but not all were < {LOWER_TH}.",
#         }
# 
#     def rewrite_query_node(state: State) -> State:
#         out = rewrite_chain.invoke({"question": state["question"]})
#         return {"web_query": out.query}
# 
#     def web_search_node(state: State) -> State:
#         q = state.get("web_query") or state["question"]
#         results = tavily.invoke({"query": q})
# 
#         web_docs: List[Document] = []
#         for r in results or []:
#             title = r.get("title", "")
#             url = r.get("url", "")
#             content = r.get("content", "") or r.get("snippet", "")
#             text = f"TITLE: {title}\nURL: {url}\nCONTENT:\n{content}"
#             web_docs.append(Document(page_content=text, metadata={"url": url, "title": title}))
# 
#         return {"web_docs": web_docs}
# 
#     def refine(state: State) -> State:
#         q = state["question"]
# 
#         if state.get("verdict") == "CORRECT":
#             docs_to_use = state["good_docs"]
#         elif state.get("verdict") == "INCORRECT":
#             docs_to_use = state["web_docs"]
#         else:  # AMBIGUOUS
#             docs_to_use = state["good_docs"] + state["web_docs"]
# 
#         context = "\n\n".join(d.page_content for d in docs_to_use).strip()
# 
#         strips = decompose_to_sentences(context)
# 
#         kept: List[str] = []
#         for s in strips:
#             if filter_chain.invoke({"question": q, "sentence": s}).keep:
#                 kept.append(s)
# 
#         refined_context = "\n".join(kept).strip()
# 
#         return {
#             "strips": strips,
#             "kept_strips": kept,
#             "refined_context": refined_context,
#         }
# 
#     answer_prompt = ChatPromptTemplate.from_messages(
#         [
#             (
#                 "system",
#                 "You are a helpful ML tutor. Answer ONLY using the provided context.\n"
#                 "If the context is empty or insufficient, say: 'I don't know.'",
#             ),
#             ("human", "Question: {question}\n\nContext:\n{context}"),
#         ]
#     )
# 
#     def generate(state: State) -> State:
#         out = (answer_prompt | llm).invoke({"question": state["question"], "context": state["refined_context"]})
#         return {"answer": out.content}
# 
#     # --- Routing (from notebook) ---
#     def route_after_eval(state: State) -> str:
#         if state["verdict"] == "CORRECT":
#             return "refine"
#         else:
#             return "rewrite_query"
# 
#     # --- Build and Compile Graph (from notebook) ---
#     g = StateGraph(State)
#     g.add_node("retrieve", retrieve_node)
#     g.add_node("eval_each_doc", eval_each_doc_node)
#     g.add_node("rewrite_query", rewrite_query_node)
#     g.add_node("web_search", web_search_node)
#     g.add_node("refine", refine)
#     g.add_node("generate", generate)
# 
#     g.add_edge(START, "retrieve")
#     g.add_edge("retrieve", "eval_each_doc")
# 
#     g.add_conditional_edges(
#         "eval_each_doc",
#         route_after_eval,
#         {
#             "refine": "refine",
#             "rewrite_query": "rewrite_query",
#         },
#     )
#     g.add_edge("rewrite_query", "web_search")
#     g.add_edge("web_search", "refine")
#     g.add_edge("refine", "generate")
#     g.add_edge("generate", END)
#     app = g.compile()
# 
#     return app
# 
# # --- Streamlit UI ---
# st.set_page_config(page_title="RAG System with LangGraph", page_icon=":robot:")
# st.title("🧠 RAG System with LangGraph")
# 
# # Load components only once
# rag_app = load_rag_components()
# 
# question = st.text_input("Ask a question:", "Batch normalization vs layer normalization")
# 
# if st.button("Get Answer"):
#     if question:
#         with st.spinner("Thinking..."):
#             initial_state = {
#                 "question": question,
#                 "docs": [],
#                 "good_docs": [],
#                 "verdict": "",
#                 "reason": "",
#                 "strips": [],
#                 "kept_strips": [],
#                 "refined_context": "",
#                 "web_query": "",
#                 "web_docs": [],
#                 "answer": "",
#             }
#             res = rag_app.invoke(initial_state)
# 
#             st.subheader("Answer:")
#             st.write(res["answer"])
# 
#             st.subheader("Details:")
#             st.write(f"**Verdict:** {res['verdict']}")
#             st.write(f"**Reason:** {res['reason']}")
#             if res['web_query']:
#                 st.write(f"**Web Search Query:** {res['web_query']}")
#             if res['web_docs']:
#                 st.write("**Web Search Results:**")
#                 for doc in res['web_docs']:
#                     st.write(f"- [{doc.metadata.get('title', 'No Title')}]({doc.metadata.get('url', '#')})")
#             if res['refined_context']:
#                 st.write("**Refined Context Used:**")
#                 st.expander("View Context").markdown(res['refined_context'])
#     else:
#         st.warning("Please enter a question.")

"""It seems the PDF files required by the Streamlit app (`book1.pdf`, `book2.pdf`, `book3.pdf`) are not present in the `/content/` directory. I will download some placeholder PDF files to this location. **Please note: These are placeholder files. You might want to replace them with your actual PDF files if they are different.**"""

# Download placeholder PDF files
!wget -O /content/book1.pdf https://www.africau.edu/images/default/sample.pdf
!wget -O /content/book2.pdf https://arxiv.org/pdf/2405.14535
!wget -O /content/book3.pdf https://arxiv.org/pdf/2405.08480

!pip install pypdf

"""The `pypdf` library has been installed. Now, please re-run the cell below to launch the Streamlit app."""

from google.colab import userdata

GROQ_API_KEY_VAL = userdata.get("GROQ_API_KEY")
TAVILY_API_KEY_VAL = userdata.get("TAVILY_API_KEY")

!GROQ_API_KEY=$GROQ_API_KEY_VAL TAVILY_API_KEY=$TAVILY_API_KEY_VAL streamlit run app.py & npx localtunnel --port 8501

"""The placeholder PDF files have been downloaded. Now, please re-run the cell below to launch the Streamlit app."""

from google.colab import userdata

GROQ_API_KEY_VAL = userdata.get("GROQ_API_KEY")
TAVILY_API_KEY_VAL = userdata.get("TAVILY_API_KEY")

!GROQ_API_KEY=$GROQ_API_KEY_VAL TAVILY_API_KEY=$TAVILY_API_KEY_VAL streamlit run app.py & npx localtunnel --port 8501

from google.colab import userdata

GROQ_API_KEY_VAL = userdata.get("GROQ_API_KEY")
TAVILY_API_KEY_VAL = userdata.get("TAVILY_API_KEY")

!GROQ_API_KEY=$GROQ_API_KEY_VAL TAVILY_API_KEY=$TAVILY_API_KEY_VAL streamlit run app.py & npx localtunnel --port 8501

!pip install streamlit

from google.colab import userdata

GROQ_API_KEY_VAL = userdata.get("GROQ_API_KEY")
TAVILY_API_KEY_VAL = userdata.get("TAVILY_API_KEY")

!GROQ_API_KEY=$GROQ_API_KEY_VAL TAVILY_API_KEY=$TAVILY_API_KEY_VAL streamlit run app.py & npx localtunnel --port 8501

!pip install -U langchain-community langchain-huggingface langchain-groq langgraph pydantic tavily-python

"""After the installation is complete, you'll need to re-run the Streamlit app cell. Please execute the cell below once the previous cell finishes."""

from google.colab import userdata

GROQ_API_KEY_VAL = userdata.get("GROQ_API_KEY")
TAVILY_API_KEY_VAL = userdata.get("TAVILY_API_KEY")

!GROQ_API_KEY=$GROQ_API_KEY_VAL TAVILY_API_KEY=$TAVILY_API_KEY_VAL streamlit run app.py & npx localtunnel --port 8501

